@startuml
hide circle
skinparam classAttributeIconSize 0

Class "<<interface>>\nParser" as Parser
Class CommentCommandParser {
  +parse(String): CommentCommand
}
Class ParseException

CommentCommandParser .up.|> Parser
CommentCommandParser .up.> CommentCommand
Parser .right.> ParseException: throws >
CommentCommandParser .right.> ParseException: throws >
@enduml
